# Generated by Django 4.1.2 on 2022-10-21 08:34

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(upload_to="", verbose_name="profile_picture"),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="description_en",
                    ),
                ),
                (
                    "description_sq",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="description_sq",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Author", "verbose_name_plural": "Authors",},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="title")),
                ("subtitle", models.CharField(max_length=20, verbose_name="subtitle")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "thumbnail",
                    models.ImageField(upload_to="", verbose_name="thumbnail"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("sq", "Shqip")],
                        default=("sq", "Shqip"),
                        max_length=20,
                        verbose_name="Language",
                    ),
                ),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                ("overview", models.TextField(verbose_name="overview")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="content"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(upload_to="", verbose_name="thumbnail"),
                ),
                ("featured", models.BooleanField(verbose_name="featured")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.author"
                    ),
                ),
                ("categories", models.ManyToManyField(to="blog.category")),
            ],
            options={"verbose_name": "Post", "verbose_name_plural": "Posts",},
        ),
    ]
