# Generated by Django 4.1.2 on 2022-10-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("sq", "Shqip")],
                default=("en", "English"),
                max_length=20,
                verbose_name="Language",
            ),
        ),
    ]
