# Generated by Django 4.1.2 on 2022-10-21 15:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_category_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "base_manager_name": "custom_manager",
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("custom_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="subtitle",
            field=models.CharField(max_length=255, verbose_name="subtitle"),
        ),
    ]
