# Generated by Django 4.1.1 on 2022-09-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default=models.CharField(max_length=100), unique=True
            ),
        ),
    ]
