# Generated by Django 4.1.1 on 2022-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="slug", field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="post", name="slug", field=models.SlugField(unique=True),
        ),
    ]
