# Generated by Django 4.1.2 on 2022-10-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_alter_post_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Post", "verbose_name_plural": "Posts"},
        ),
        migrations.AlterModelManagers(name="post", managers=[],),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(related_name="posts", to="blog.category"),
        ),
    ]
