# Generated by Django 4.1.1 on 2022-10-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_category_slug_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="category",
            name="subtitle",
            field=models.CharField(max_length=20, verbose_name="subtitle"),
        ),
        migrations.AlterField(
            model_name="category",
            name="thumbnail",
            field=models.ImageField(upload_to="", verbose_name="thumbnail"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=20, verbose_name="title"),
        ),
    ]
