# Generated by Django 4.1.1 on 2022-10-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_category_slug_alter_category_subtitle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profile_picture",
            field=models.ImageField(upload_to="", verbose_name="profile_picture"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="post",
            name="featured",
            field=models.BooleanField(verbose_name="featured"),
        ),
        migrations.AlterField(
            model_name="post",
            name="overview",
            field=models.TextField(verbose_name="overview"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(upload_to="", verbose_name="thumbnail"),
        ),
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
    ]
