# Generated by Django 4.1.1 on 2022-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_author_profile_picture_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("sq", "Shqip")],
                default=("sq", "Shqip"),
                max_length=20,
                verbose_name="Language",
            ),
        ),
    ]
