# Generated by Django 4.1.1 on 2022-10-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="language",),
        migrations.AddField(
            model_name="category",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("sq", "Shqip")],
                default=("sq", "Shqip"),
                max_length=20,
                verbose_name="Language",
            ),
        ),
    ]
