# Generated by Django 4.1.1 on 2022-10-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_author_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="description_('en', 'English')",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Description"
            ),
        ),
    ]
