# Generated by Django 4.1.1 on 2022-10-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_author_description_('en', 'english')"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author", name="description_('en', 'English')",
        ),
        migrations.RemoveField(
            model_name="author", name="description_('sq', 'Albanian')",
        ),
        migrations.AddField(
            model_name="author",
            name="description_en",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Description_en"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="description_sq",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Description_sq"
            ),
        ),
    ]
