# Generated by Django 4.1.1 on 2022-10-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_remove_author_description_('en', 'english')_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="description_en",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description_en"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="description_sq",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description_sq"
            ),
        ),
    ]
